FROM ruby:3.2.2-alpine3.18

# Install dependencies
RUN apk add --no-cache build-base

# Install Sidekiq
RUN gem install sidekiq:7.1.6 redis

# Set the working directory
WORKDIR /app

# Copy the Sidekiq config and worker definitions
COPY sidekiq.rb /app/sidekiq.rb
COPY sidekiq.yml /app/sidekiq.yml

CMD ["sidekiq", "-r", "/app/sidekiq.rb", "-C", "/app/sidekiq.yml"]