FROM ruby:2.7.8-alpine3.16

# Install dependencies
RUN apk add --no-cache build-base

# Install Sidekiq
RUN gem install sidekiq:6.5.9 redis

# Set the working directory
WORKDIR /app

# Copy the Sidekiq config and worker definitions
COPY sidekiq.rb /app/sidekiq.rb
COPY sidekiq.yml /app/sidekiq.yml

CMD ["sidekiq", "-r", "/app/sidekiq.rb", "-C", "/app/sidekiq.yml"]
