FROM ruby:2.6.10-alpine3.15

# Install dependencies
RUN apk add --no-cache build-base

# Install Sidekiq
RUN gem install sidekiq:5.2.10 redis

# Set the working directory
WORKDIR /app

# Copy the Sidekiq config and worker definitions
COPY sidekiq.rb /app/sidekiq.rb
COPY sidekiq.yml /app/sidekiq.yml

CMD ["sidekiq", "-r", "/app/sidekiq.rb", "-C", "/app/sidekiq.yml"]