version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
    exclude_paths:
    - spec/
  rubocop:
    enabled: true
    channel: rubocop-0-58
exclude_paths:
- tmp/
- gemfiles/
