---
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: ~

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Appraisals"
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
    - "spec/spec_helper.rb"
    - "spec/**/*_spec.rb"
    - "**/*.gemspec"
    - "**/*.rake"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/RedundantFreeze:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate
  Exclude:
    - "spec/**/*"

Style/NumericLiterals:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: ~

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: ~

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "spec/**/*.rb"

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/StructNewOverride:
  Exclude:
    - "lib/sidekiq/prometheus/exporter/standard.rb"

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/FilePath:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ScatteredSetup:
  Enabled: true

Rake/Desc:
  Enabled: false
