# This file was generated by Appraisal

source "https://rubygems.org"

gem "slim"
gem "redis", "~> 3.3"
gem "redis-namespace", "< 1.7.0"
gem "sinatra"
gem "concurrent-ruby"
gem "sidekiq", "= 3.3.1"

gemspec path: "../"
