# This file was generated by Appraisal

source "https://rubygems.org"

gem "appraisal", "~> 2.2"
gem "bundler", "~> 2.1"
gem "pry", "~> 0.14"
gem "pry-byebug", "~> 3.6"
gem "rack-test", ">= 1.1"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.22"
gem "rubocop-performance", "~> 1.12"
gem "rubocop-rake", "~> 0.6"
gem "rubocop-rspec", "~> 2.6"
gem "timecop", "~> 0.9"
gem "sidekiq", "~> 8.0"

gemspec path: "../"
