# This file was generated by Appraisal

source "https://rubygems.org"

gem "rack", ">= 2", git: "https://github.com/rack/rack"
gem "redis", ">= 4", git: "https://github.com/redis/redis-rb"
gem "sidekiq", ">= 7", git: "https://github.com/mperham/sidekiq"

gemspec path: "../"
