{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "sidekiq-prometheus-exporter.fullname" . }}
  labels:
    {{- include "sidekiq-prometheus-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
    {{- if eq .Values.externalEnvVars.type "Secret" }}
    - "secrets"
    {{- else }}
    - "configmap"
    {{- end }}
    resourceNames: ["{{ .Values.externalEnvVars.name }}"]
    verbs: ["get"]
{{- end }}
