{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sidekiq-prometheus-exporter.fullname" . }}
  labels:
    {{- include "sidekiq-prometheus-exporter.labels" . | nindent 4 }}
{{- end }}
