{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "sidekiq-prometheus-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "sidekiq-prometheus-exporter.labels" . | indent 4 }}
{{- with .Values.servicemonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  jobLabel: {{ template "sidekiq-prometheus-exporter.fullname" . }}
  selector:
    matchLabels:
{{ include "sidekiq-prometheus-exporter.labels" . | indent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: metrics
    path: {{ .Values.servicemonitor.path }}
    interval: {{ .Values.servicemonitor.interval }}
    scrapeTimeout: {{ .Values.servicemonitor.scrapeTimeout }}
{{- end }}
