{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sidekiq-prometheus-exporter.fullname" . }}
  labels:
{{ include "sidekiq-prometheus-exporter.labels" . | indent 4 }}
  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
