---
version: "3.4"

services:
  metrics:
    build:
      context: ./metrics
      dockerfile: Dockerfile.sidekiq-8x
    # NOTE: This makes local gem to load before installed gem
    # environment:
    #   - LOCAL=1
    volumes:
      - ../.:/sidekiq-prometheus-exporter
      - ./metrics/config.ru:/config.ru
    ports:
      - 9292:9292
    depends_on:
      - sidekiq
      - redis

  sidekiq:
    build:
      context: ./sidekiq
      dockerfile: Dockerfile.sidekiq-8x
    volumes:
      - ./sidekiq/sidekiq.rb:/sidekiq.rb
      - ./sidekiq/sidekiq.yml:/sidekiq.yml
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - metrics

  grafana:
    image: grafana/grafana:11.4.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  redis:
    image: redis:7.2.7-alpine

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
