FROM ruby:2.6.10-alpine3.15

# Install dependencies
RUN apk add --no-cache build-base

# Install required gems
RUN gem install rack:2.0.9 rackup:0.2.3 webrick:1.6.1 sidekiq:5.2.10 redis-namespace:1.8.2 sidekiq-prometheus-exporter:0.3.0

# Set the working directory
WORKDIR /app

# Copy the config file
COPY config.ru /app/config.ru

EXPOSE 9292
CMD ["rackup", "-E", "production", "-p", "9292", "-o", "0.0.0.0", "config.ru"]