FROM ruby:3.2.2-alpine3.18

# Install dependencies
RUN apk add --no-cache build-base

# Install required gems
RUN gem install rack:2.2.8 rackup:2.1.0 webrick:1.8.1 sidekiq:7.1.6 redis-namespace:1.11.0 sidekiq-prometheus-exporter:0.3.0

# Set the working directory
WORKDIR /app

# Copy the config file
COPY config.ru /app/config.ru

EXPOSE 9292
CMD ["rackup", "-E", "production", "-p", "9292", "-o", "0.0.0.0", "config.ru"]