FROM ruby:3.3.7-alpine

RUN apk add --update build-base

RUN gem install webrick -v "~> 1.9"
RUN gem install sidekiq -v "~> 6.0"
RUN gem install sidekiq-prometheus-exporter -v "~> 0.1"

ENTRYPOINT [ "rackup" ]
CMD [ "-p", "9292", "-o", "0.0.0.0", "/config.ru" ]
