---
name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rake:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          reporter: github-pr-review
          fail_on_error: true

  test:
    needs: rubocop
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Sidekiq ${{ matrix.sidekiq }}
    strategy:
      matrix:
        # Always keep a window of "5 most recent" including (or on top with) HEAD
        ruby: ["2.6.10", "2.7.6", "3.0.4", "3.1.2", "latest"]
        sidekiq: ["3.3.1", "3.x", "4.x", "5.x", "6.x", "latest"]
        # Allow failures ... kind-a
        exclude:
          - ruby: "2.6.10"
            sidekiq: "latest"
          - ruby: "2.7.6"
            sidekiq: "latest"
          - ruby: "3.0.4"
            sidekiq: "latest"
          - ruby: "3.1.2"
            sidekiq: "latest"

    container:
      image: ruby:${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: bundle-${{ matrix.ruby }}-sidekiq-${{ matrix.sidekiq }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/.*Gemfile.lock') }}

      - name: Upgrade Bundler to 2.x (for older Ruby versions)
        run: gem install bundler -v '~> 2.1'

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle config gemfile gemfiles/sidekiq_${{ matrix.sidekiq }}.Gemfile
          bundle install

      - name: Run RSpec
        run: bundle exec rake spec
